(function () {
  'use strict';
  var GAME_CLASSES = {
    guerreiro: { id: 'guerreiro', nome: 'Guardião de Cristal', tipoIcone: '???', corPrimaria: '#C0392B', corSecundaria: '#D4AF37', especialidade: { critico: 1, mobilidade: 2, defesa: 5 }, idleDescricao: 'Respiração pesada. Escudo à frente, espada apontada para baixo. Partículas vermelhas sobem ao redor.', corParticulaIdle: '#E74C3C', habilidades: [{ id: 'muralha_divina', nome: 'Muralha Divina', descricao: 'Finca o escudo no chão.', cooldown: 20000, visual: { tipo: 'barreira', cor: '#D4AF37' } }, { id: 'impacto_colossal', nome: 'Impacto Colossal', descricao: 'Salta e cai violentamente.', cooldown: 16000, visual: { tipo: 'impacto_solo', cor: '#E74C3C' } }, { id: 'escudo_espelhado', nome: 'Escudo Espelhado', descricao: 'Reflete projéteis.', cooldown: 25000, visual: { tipo: 'espelho', cor: '#F1C40F' } }], ultimate: { id: 'fortaleza_guardiao', nome: 'Fortaleza do Guardião', descricao: 'Castelo de cristal ao redor do grupo.', cooldown: 90000, visual: { tipo: 'fortaleza', cor: '#D4AF37' } } },
    arqueiro: { id: 'arqueiro', nome: 'Caçador Celestial', tipoIcone: '??', corPrimaria: '#1E8449', corSecundaria: '#17A2B8', especialidade: { critico: 5, mobilidade: 4, defesa: 2 }, idleDescricao: 'Arco preparado, asas vibram suavemente.', corParticulaIdle: '#2ECC71', habilidades: [{ id: 'flecha_fantasma', nome: 'Flecha Fantasma', descricao: 'Divide-se em 12 flechas.', cooldown: 12000, visual: { tipo: 'flecha_dividida', cor: '#2ECC71' } }, { id: 'tempestade_mil_flechas', nome: 'Tempestade de Mil Flechas', descricao: 'Invoca centenas de flechas mágicas.', cooldown: 22000, visual: { tipo: 'chuva_flechas', cor: '#16A085' } }, { id: 'instinto_mortal', nome: 'Instinto Mortal', descricao: 'Buff de +70% crítico.', cooldown: 18000, visual: { tipo: 'buff_aura', cor: '#1ABC9C' } }], ultimate: { id: 'eclipse_cacador', nome: 'Eclipse do Caçador', descricao: 'Dispara centenas de flechas simultâneas.', cooldown: 95000, visual: { tipo: 'eclipse', cor: '#0B5345' } } },
    mago: { id: 'mago', nome: 'Sábio Arcano', tipoIcone: '??', corPrimaria: '#5DADE2', corSecundaria: '#8E44AD', corTerciaria: '#FFFFFF', especialidade: { cura: 5, magia: 4, controle: 2 }, idleDescricao: 'O cajado flutua, runas giram, pequenos cristais orbitam.', corParticulaIdle: '#AF7AC5', habilidades: [{ id: 'chuva_celestial', nome: 'Chuva Celestial', descricao: 'Chuva de meteoros que aplica lentidão.', cooldown: 20000, visual: { tipo: 'meteoros', cor: '#5DADE2' } }, { id: 'cura_suprema', nome: 'Cura Suprema', descricao: 'Cura em área e regeneração.', cooldown: 24000, visual: { tipo: 'circulo_cura', cor: '#FFFFFF' } }, { id: 'prisma_arcano', nome: 'Prisma Arcano', descricao: 'Feixe mágico que se divide.', cooldown: 16000, visual: { tipo: 'prisma', cor: '#8E44AD' } }], ultimate: { id: 'santuario_celestial', nome: 'Santuário Celestial', descricao: 'Uma árvore de cristal gigante que cura e protege.', cooldown: 100000, visual: { tipo: 'arvore_cristal', cor: '#FFFFFF' } } }
  };
  var WING_LEVELS = [{ nivel: 1, nome: 'Cristal Bruto', minXp: 0 }, { nivel: 2, nome: 'Cristal Refinado', minXp: 500 }, { nivel: 3, nome: 'Cristal Celestial', minXp: 2000 }, { nivel: 4, nome: 'Cristal Divino', minXp: 6000 }, { nivel: 5, nome: 'Asa Suprema', minXp: 15000 }];
  var XP_TABLE = {}; for (let i = 1; i <= 80; i++) { XP_TABLE[i] = Math.floor(100 * Math.pow(i, 1.8)); }
  var MONSTERS = [{ id: 1, nome: 'Cristal Corrompido', hpBase: 100, xp: 20 }, { id: 2, nome: 'Sentinela de Aço', hpBase: 250, xp: 50 }, { id: 3, nome: 'Guardião Abissal', hpBase: 600, xp: 150 }];
  var EXPORTS = { GAME_CLASSES, WING_LEVELS, XP_TABLE, MONSTERS };
  if (typeof module !== 'undefined' && module.exports) { module.exports = EXPORTS; } else { window.GAME_CLASSES = GAME_CLASSES; window.WING_LEVELS = WING_LEVELS; window.XP_TABLE = XP_TABLE; window.MONSTERS = MONSTERS; }
})();
